In [1]:
import torch
import numpy as np

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)


tensor([[1, 2],
        [3, 4]])


In [7]:
tensor = x_data
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is Stored on: {tensor.device}")

tensor[:,1] =0
print(tensor)

y1= tensor@tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is Stored on: cpu
tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])
